'use strict';

(function () {
  var MIN_SCALE_VALUE = 25;
  var MAX_SCALE_VALUE = 100;
  var CHANGE_SCALE_STEP = 25;
  var MAX_HASHTAGS_COUNT = 5;
  var MAX_HASHTAG_LENGTH = 20;

  window.config = {
    MIN_SCALE_VALUE: MIN_SCALE_VALUE,
    MAX_SCALE_VALUE: MAX_SCALE_VALUE,
    CHANGE_SCALE_STEP: CHANGE_SCALE_STEP,
    MAX_HASHTAGS_COUNT: MAX_HASHTAGS_COUNT,
    MAX_HASHTAG_LENGTH: MAX_HASHTAG_LENGTH
  };
})();
